version: '3'
services:
  client:
    build: ./client
    container_name: react-app
    ports:
      - '3000:3000'
  server:
    build: ./server
    container_name: express-mysql
    ports:
      - '3001:3001'
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 98421234aQ!
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '3306:3306'
