version: '3'
services:
  server:
    build: .
    container_name: express-mysql
    ports:
      - '3001:3001'
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 98421234aQ!
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '3308:3306'
